"""Generate the site's English MP3s offline with Kokoro v1.0 / af_heart.

Install CPU torch, kokoro==0.9.4, transformers<5, soundfile, en_core_web_sm,
and ffmpeg. Download config.json, kokoro-v1_0.pth, and voices/af_heart.pt
from https://huggingface.co/hexgrad/Kokoro-82M into --model-dir.
"""
import argparse
import concurrent.futures
import hashlib
import json
import multiprocessing
from pathlib import Path
import re
import subprocess
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'public/audio/examples'
PIPELINE = None
VOICE = None


def initialize(model_dir):
    import torch
    from kokoro import KModel, KPipeline
    global PIPELINE, VOICE
    torch.set_num_threads(1)
    torch.set_num_interop_threads(1)
    model_dir = Path(model_dir)
    model = KModel(repo_id='hexgrad/Kokoro-82M', config=str(model_dir/'config.json'),
                   model=str(model_dir/'kokoro-v1_0.pth')).eval()
    PIPELINE = KPipeline(lang_code='a', repo_id='hexgrad/Kokoro-82M', model=model)
    VOICE = torch.load(model_dir/'af_heart.pt', weights_only=True)


def render(item):
    import numpy as np
    import soundfile as sf
    key, text = item
    text = re.sub(r'[\u3400-\u9fff]', '', text).replace('&', ' and ')
    text = re.sub(r'\s+', ' ', text).strip()
    digest = hashlib.sha256(('kokoro-v1.0-af_heart|' + text).encode()).hexdigest()[:16]
    target = OUTPUT / f'{key}-{digest}.mp3'
    if not target.exists():
        chunks = [result.audio.numpy() for result in PIPELINE(text, voice=VOICE, speed=1.0)]
        samples = np.concatenate(chunks)
        assert np.isfinite(samples).all() and np.max(np.abs(samples)) > .001
        assert len(samples) / 24000 > 1
        with tempfile.TemporaryDirectory() as temp:
            wav, mp3 = Path(temp)/'audio.wav', Path(temp)/'audio.mp3'
            sf.write(wav, samples, 24000)
            subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', str(wav),
                            '-codec:a', 'libmp3lame', '-b:a', '64k', '-ac', '1', str(mp3)], check=True)
            target.write_bytes(mp3.read_bytes())
    assert target.stat().st_size > 1000
    return key, '/audio/examples/' + target.name


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model-dir', required=True)
    parser.add_argument('--workers', type=int, default=4)
    parser.add_argument('--limit', type=int)
    args = parser.parse_args()
    data = json.loads((ROOT/'app/exampleData.ts').read_text().split(' = ', 2)[2].strip().rstrip(';'))
    items = [(key, value['english'].strip()) for key, value in data.items() if value['english'].strip()]
    if args.limit:
        items = items[:args.limit]
    OUTPUT.mkdir(parents=True, exist_ok=True)
    results = {}
    started = time.monotonic()
    with concurrent.futures.ProcessPoolExecutor(max_workers=args.workers,
            mp_context=multiprocessing.get_context('spawn'),
            initializer=initialize, initargs=(args.model_dir,)) as executor:
        futures = [executor.submit(render, item) for item in items]
        for future in concurrent.futures.as_completed(futures):
            key, url = future.result()
            results[key] = url
            if len(results) % 20 == 0 or len(results) == len(items):
                print(f'{len(results)}/{len(items)} generated in {time.monotonic()-started:.0f}s', flush=True)
    if not args.limit:
        (ROOT/'app/exampleAudio.ts').write_text(
            '// Generated by scripts/generate-example-audio.py; Kokoro v1.0, af_heart.\n'
            'export const EXAMPLE_AUDIO: Record<string, string> = ' +
            json.dumps(dict(sorted(results.items())), indent=2) + ';\n')
    else:
        print(json.dumps(results), flush=True)
